<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ToDoListNTier.DAL\ToDoListNTier.DAL.csproj" />
    <ProjectReference Include="..\ToDoListNTier.Models\ToDoListNTier.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.6.0" />
  </ItemGroup>

</Project>
